apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: certs2secrets
  name: certs2secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certs2secrets
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: certs2secrets
    spec:
      serviceAccountName: certs2secrets
      containers:
      - env:
        - name: APP_NAME
          value: "etcd-cluster"
        - name: SLEEP_TIME
          value: "60"
        - name: CLUSTER_FQDN
          value: "portworx-etcd-cluster.portworx.svc"
        - name: CLIENT_CERT
          value: "true"
        - name: PEER_CERT
          value: "true"
        - name: SERVER_CERT
          value: "true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/mauilion/certs2secrets:v1.11.0
        name: certs2secrets
        resources: {}
status: {}
