apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: certs2secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certs2secrets
subjects:
- kind: ServiceAccount
  name: certs2secrets
  namespace: portworx