apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: certs2secrets
rules:

- apiGroups:
  - "certificates.k8s.io"
  resources:
  - "certificatesigningrequests"
  - "certificatesigningrequests/approval"
  - "certificatesigningrequests/status"
  verbs:
  - update
  - create
  - get
  - delete

- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]

- apigroups: [""]
  resources: ["secrets"]
  verbs:
  - create
  - get
  - update
